### ISSUE TITLE
Some arc won't be drawn right

### ISSUE THREAD

**Issue by Athesis** [mduggan/dxf2svg#1]
Hi,

I found a problem that some ARCs won't be drawn right. 

Here is the Input-File and from dxf2svg generated Output-File:
[debug.zip](https://github.com/mduggan/dxf2svg/files/684080/debug.zip)

I located the possible source of the bug (entities2elements.cpp from line 268 to 273)  but I didn't found a solution that dosn't break every other arc.

Would be great to find here a solution together

**Comment by mduggan** [comment]
Hi! Sorry, I haven't really looked at this code for a long time, I kinda got it working for the file I had and then let it rot.  Unfortunately I don't have much time to look at this at the moment, but if you find the source of the problem I'd be happy to take a patch - otherwise I will try to look at it when I have some time.

**Comment by Athesis** [comment]
Hi,

Replacing 

```
// Determine if it is a large arc
	if ( (a.ret_end_ang() > a.ret_srt_ang()) && ( (a.ret_end_ang() - a.ret_srt_ang()) > 180) ){
		strcat(out," 1,0 "); // Large arc flag...Always use a zero sweep flag
	}
	else{
		strcat(out," 0,0 "); // Small arc flag...Always use a zero sweep flag
}
```



with
```
	// Determine if it is a large arc
	if ((a.ret_end_ang() > a.ret_srt_ang()) && ((a.ret_srt_ang() - a.ret_end_ang()) >= 180)){
		strcat(out, " 1,0 "); // Large arc flag...Always use a zero sweep flag
	}
	else if ((a.ret_end_ang() < a.ret_srt_ang()) && ((360 + a.ret_end_ang() - a.ret_srt_ang()) >= 180)){
		strcat(out, " 1,0 "); // Large arc flag...Always use a zero sweep flag
	}
	else{
		strcat(out, " 0,0 "); // Small arc flag...Always use a zero sweep flag
	}
```

should do the trick!

**Comment by Athesis** [comment]
```
meep
,eepp
```

**Comment by mduggan** [comment]
Thanks for the fix, I got to it eventually :)
